export const columns = [
    { title: 'Name', field: 'name' },
    { title: 'Address', field: 'address' },
    { title: 'TTL', field: 'ttl', type: 'numeric' },
    {
        title: 'Type',
        field: 'type',
        lookup: {
            0x01: 'A',
            0x02: 'NS',
            0x03: 'MD',
            0x04: 'MF',
            0x05: 'CNAME',
            0x06: 'SOA',
            0x07: 'MB',
            0x08: 'MG',
            0x09: 'MR',
            0x0a: 'NULL',
            0x0b: 'WKS',
            0x0c: 'PTR',
            0x0d: 'HINFO',
            0x0e: 'MINFO',
            0x0f: 'MX',
            0x10: 'TXT',
            0x1c: 'AAAA',
            0x21: 'SRV',
            0x29: 'EDNS',
            0x63: 'SPF',
            0xfc: 'AXFR',
            0xfd: 'MAILB',
            0xfe: 'MAILA',
            0xff: 'ANY',
            0x101: 'CAA',
        },
    },
    {
        title: 'Class',
        field: 'class',
        lookup: {
            0x01: 'IN',
            0x02: 'CS',
            0x03: 'CH',
            0x04: 'HS',
            0xff: 'ANY',
        },
    },
]
